[project]
name = "findingmodel"
version = "0.6.1"
description = "Definition and tools for Open Imaging Finding Models"
authors = [
    { name = "Tarik Alkasab", email = "tarik@alkasab.org" },
    { name = "Vijay Dawal", email = "vijaydawal@microsoft.com" },
]
requires-python = ">=3.11"
readme = "../../README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
keywords = [
    "finding model",
    "common data element",
    "medical imaging",
    "data model",
    "radiology"
]

dependencies = [
    "click>=8.1.8",
    "jinja2>=3.1.6",
    "openai>=1.76",
    "platformdirs>=4.0.0",
    "pooch>=1.8.0",
    "pydantic[email]>=2.11.3",
    "pydantic-settings>=2.9.1",
    "rich>=13.9.4",
    "prompt-toolkit>=3.0.48",
    "loguru>=0.7.3",
    "pydantic-ai-slim[openai,tavily,anthropic,google]>=0.3.2",
    "tavily-python>=0.6.0",
    "duckdb>=1.3.2",
    "httpx>=0.28.0",
    "mcp>=1.0.0",
    "boto3>=1.40.75",
    "boto3-stubs[s3]>=1.40.75",
]

[project.urls]
Homepage = "https://github.com/openimagingdata/findingmodel"
Issues = "https://github.com/openimagingdata/findingmodel/issues"

[project.scripts]
fm-tool = "findingmodel.cli:cli"
findingmodel-mcp = "findingmodel.mcp_server:main"

[build-system]
requires = ["uv_build>=0.7.19,<0.8.0"]
build-backend = "uv_build"
